import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Footer } from "@/components/footer";


export const metadata: Metadata = {
  title: "RubySwap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen bg-gradient-to-r from-green-900 via-black to-green-900">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
